arangodb:
  hosts: localhost
  database: sample
  maxconnections: 10
  usessl: true

logging:
  level:
    org.springframework.web: INFO
    com.hpe.gravity.client.state.graphql.service: INFO

features:
  CNX-1128:
    description: "Support to view the list of Unified Clients for wired/wireless client"
    enable: false
  CNX-1132:
    description: "Pre-canned filters based on connection status for ClientList View"
    enable: false